// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rpk_back.Application.Db;

namespace Rpk_back.WebAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201024155925_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Rpk_back.Domain.Models.Sensor", b =>
                {
                    b.Property<Guid>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Localization")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SensorGroupGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.Property<float>("SensorValue")
                        .HasColumnType("real");

                    b.HasKey("SensorId");

                    b.ToTable("SensorItems");
                });
#pragma warning restore 612, 618
        }
    }
}
